#region MITRE ATT&CK labels and Navigator layer

# The pinned catalog (data/attack/attack-catalog.json) is generated by build/Import-AttackCatalog.ps1
# from MITRE's official releases; IDs are never typed from memory (tests/Attack.Tests.ps1).
$script:VsatAttackNavigatorVersion = '5.3.2'   # latest ATT&CK Navigator release when the layer format was checked
$script:VsatAttackLayerVersion = '4.5'

function Get-VsatAttackCatalog {
    if (-not $script:VsatAttackCatalogCache) { $script:VsatAttackCatalogCache = ConvertFrom-VsatJson (Get-VsatEmbeddedText 'data/attack/attack-catalog.json') }
    return $script:VsatAttackCatalogCache
}

function Get-VsatAttackEdgeMappings {
    if (-not $script:VsatAttackEdgeMapCache) { $script:VsatAttackEdgeMapCache = @((ConvertFrom-VsatJson (Get-VsatEmbeddedText 'data/attack/edge-techniques.json')).mappings) }
    return $script:VsatAttackEdgeMapCache
}

function Test-VsatAttackTechniqueUsable {
    param([string]$Id)
    $c = Get-VsatAttackCatalog
    if (-not $Id -or -not $c.techniques.Contains($Id)) { return $false }
    $t = $c.techniques[$Id]
    return (-not [bool]$t.revoked -and -not [bool]$t.deprecated)
}

function Get-VsatAttackTechniqueName {
    # Display name as ATT&CK writes it: "Parent: Sub-technique" for sub-techniques.
    param([string]$Id)
    $c = Get-VsatAttackCatalog
    if (-not $c.techniques.Contains($Id)) { return $null }
    $n = [string]$c.techniques[$Id].name
    $dot = $Id.LastIndexOf('.')
    if ($Id -match '^T\d{4}\.\d{3}$' -and $c.techniques.Contains($Id.Substring(0, $dot))) { return "$([string]$c.techniques[$Id.Substring(0, $dot)].name): $n" }
    return $n
}

function Test-VsatAttackWhen {
    param($When, $Edge, $Graph)
    if (-not $When) { return $true }
    $list = { param($v) @($v | Where-Object { $null -ne $_ } | ForEach-Object { [string]$_ }) }
    $nodeType = {
        param([string]$id)
        if ($Graph -and $Graph.nodes -and $Graph.nodes.ContainsKey($id)) { return [string]$Graph.nodes[$id].type }
        return ''
    }
    if ($When.Contains('sourcePrefix')) {
        $src = [string]$Edge.source
        if (-not @(& $list $When.sourcePrefix | Where-Object { $src.StartsWith($_, [StringComparison]::Ordinal) }).Count) { return $false }
    }
    if ($When.Contains('sourceType') -and (& $nodeType ([string]$Edge.source)) -notin @(& $list $When.sourceType)) { return $false }
    if ($When.Contains('targetType') -and (& $nodeType ([string]$Edge.target)) -notin @(& $list $When.targetType)) { return $false }
    if ($When.Contains('port')) {
        $ports = @(Get-VsatProp $Edge 'ports' @() | ForEach-Object { [int]$_ })
        if ([int]$When.port -notin $ports) { return $false }
    }
    return $true
}

function Get-VsatAttackForEdge {
    # First matching mapping wins. Returns @{ technique; name; mappingStatus } or $null (no technique,
    # e.g. embodies, or a mapped ID that is not usable in the pinned catalog).
    param([Parameter(Mandatory)]$Edge, $Graph)
    foreach ($m in (Get-VsatAttackEdgeMappings)) {
        if ([string]$m.kind -ne [string]$Edge.kind) { continue }
        if (-not (Test-VsatAttackWhen -When (Get-VsatProp $m 'when' $null) -Edge $Edge -Graph $Graph)) { continue }
        $t = [string](Get-VsatProp $m 'technique' '')
        if (-not $t -or -not (Test-VsatAttackTechniqueUsable $t)) { return $null }
        return [ordered]@{ technique = $t; name = (Get-VsatAttackTechniqueName $t); mappingStatus = [string]$m.status }
    }
    return $null
}

# Label every graph edge as it is created (Add-VsatGraphEdge), lazily added ones included (P9).
$script:VsatEdgeAttackHook = { param($Edge, $Graph) Get-VsatAttackForEdge -Edge $Edge -Graph $Graph }

function New-VsatAttackLayer {
    # ATT&CK Navigator layer (format 4.5, enterprise-attack). Score per technique = open Blast Radius
    # paths with a hop labelled with it + FAIL findings whose rule mitigates it. Techniques with score 0
    # are omitted, and so are ATLAS (AML.*) IDs, which the enterprise Navigator does not know.
    param([Parameter(Mandatory)]$Results)
    $cat = Get-VsatAttackCatalog
    $hits = @{}
    $add = {
        param([string]$tid, [string]$kind, [string]$id)
        if (-not $tid -or -not $id -or $tid -notmatch '^T\d{4}(\.\d{3})?$' -or -not (Test-VsatAttackTechniqueUsable $tid)) { return }
        if (-not $hits.ContainsKey($tid)) { $hits[$tid] = @{ paths = [System.Collections.Generic.List[string]]::new(); findings = [System.Collections.Generic.List[string]]::new() } }
        $l = $hits[$tid][$kind]
        if (-not $l.Contains($id)) { $l.Add($id) }
    }
    $br = Get-VsatProp $Results 'analysis.blastRadius' $null
    if ($br) {
        $eb = @{}; foreach ($e in @($br.edges)) { if ($e) { $eb[[string]$e.id] = $e } }
        foreach ($p in @($br.paths)) {
            if (-not $p) { continue }
            foreach ($eid in @($p.edgeIds)) {
                $e = $eb[[string]$eid]
                $at = if ($e) { Get-VsatProp $e 'attack' $null } else { $null }
                if ($at) { & $add ([string](Get-VsatProp $at 'technique' '')) 'paths' ([string]$p.id) }
            }
        }
    }
    $ruleAttack = @{}
    foreach ($r in @($Results.rules)) { if ($r -and (Get-VsatProp $r 'attack' $null)) { $ruleAttack[[string]$r.id] = $r.attack } }
    if (-not $ruleAttack.Count) { foreach ($r in @((Get-VsatRulePack).rules)) { if ($r.Contains('attack')) { $ruleAttack[[string]$r.id] = $r.attack } } }
    foreach ($f in @($Results.findings)) {
        if (-not $f -or $f.result -ne 'FAIL' -or -not $ruleAttack.ContainsKey([string]$f.ruleId)) { continue }
        foreach ($tid in @(Get-VsatProp $ruleAttack[[string]$f.ruleId] 'mitigates' @())) { & $add ([string]$tid) 'findings' ([string]$f.id) }
    }
    $ids = [string[]]@($hits.Keys); [Array]::Sort($ids, [StringComparer]::Ordinal)
    $max = 1
    $techniques = foreach ($tid in $ids) {
        $h = $hits[$tid]
        $score = $h.paths.Count + $h.findings.Count
        if ($score -le 0) { continue }
        if ($score -gt $max) { $max = $score }
        $parts = [System.Collections.Generic.List[string]]::new()
        if ($h.paths.Count) { $parts.Add("$($h.paths.Count) open attack path(s): $(@($h.paths | Select-Object -First 5) -join ', ')$(if ($h.paths.Count -gt 5) { ", +$($h.paths.Count - 5) more" })") }
        if ($h.findings.Count) { $parts.Add("$($h.findings.Count) failing control(s): $(@($h.findings | Select-Object -First 5) -join ', ')$(if ($h.findings.Count -gt 5) { ", +$($h.findings.Count - 5) more" })") }
        [ordered]@{ techniqueID = $tid; score = [int]$score; comment = "$(Get-VsatAttackTechniqueName $tid). $($parts -join '; ')."; enabled = $true }
    }
    $ver = [string]$cat.source.attack.version
    $run = Get-VsatProp $Results 'run' $null
    $runId = [string](Get-VsatProp $run 'id' '')
    return [ordered]@{
        name = "VSAT $(if ($runId) { $runId } else { 'assessment' })"
        versions = [ordered]@{ attack = ($ver -split '\.')[0]; navigator = $script:VsatAttackNavigatorVersion; layer = $script:VsatAttackLayerVersion }
        domain = 'enterprise-attack'
        description = "VSAT $script:VsatVersion ($([string](Get-VsatProp $Results 'status.label' ''))). Score = open Blast Radius attack paths that use the technique + failing VSAT controls that mitigate it. Technique IDs from the pinned MITRE ATT&CK Enterprise $ver catalog; mappings are VSAT proposals until reviewed."
        sorting = 3
        layout = [ordered]@{ layout = 'side'; showID = $true; showName = $true; showAggregateScores = $false; countUnscored = $false; aggregateFunction = 'max'; expandedSubtechniques = 'annotated' }
        hideDisabled = $false
        techniques = @($techniques)
        gradient = [ordered]@{ colors = @('#fff3e0', '#f57c00', '#b71c1c'); minValue = 0; maxValue = [int]$max }
        legendItems = @(
            [ordered]@{ label = 'Few open paths / failing controls'; color = '#fff3e0' }
            [ordered]@{ label = 'Many open paths / failing controls'; color = '#b71c1c' }
        )
        metadata = @(
            [ordered]@{ name = 'Generated by'; value = "VSAT $script:VsatVersion" }
            [ordered]@{ name = 'Run'; value = $(if ($runId) { $runId } else { 'n/a' }) }
            [ordered]@{ name = 'ATT&CK catalog'; value = "Enterprise $ver (sha256 $([string]$cat.source.attack.sha256))" }
        )
        showTacticRowBackground = $false
        selectTechniquesAcrossTactics = $true
        selectSubtechniquesWithParent = $false
        selectVisibleTechniques = $false
    }
}

#endregion MITRE ATT&CK labels and Navigator layer
