#region Compliance crosswalk
# data/frameworks (generated by build/New-CrosswalkSeed.ps1): framework catalogs (control IDs plus
# VSAT-written paraphrases, never standards text) and the rule -> control crosswalk with provenance.
# A mapping is "verified" only with reviewer, review date, source reference and a confirmed framework
# edition. The loader never trusts a verified row without them: it is shown as proposed instead.

$script:VsatCrosswalkCache = $null
# Matrix states, worst first. Missing evidence (UNKNOWN/ERROR) is never satisfied.
$script:VsatMatrixStates = @('not-satisfied', 'not-assessed', 'manual-open', 'excepted', 'partial', 'manual-signed-off', 'satisfied')

function Test-VsatMappingProvenance {
    # Returns the reasons a mapping marked verified is not provably verified (empty when it is, or
    # when it does not claim to be verified). This is the verified-mapping gate.
    param([Parameter(Mandatory)]$Mapping, [Parameter(Mandatory)]$Catalogs)
    if ([string](Get-VsatProp $Mapping 'status' '') -ne 'verified') { return @() }
    $why = [System.Collections.Generic.List[string]]::new()
    if (-not [string](Get-VsatProp $Mapping 'reviewer' '')) { $why.Add('no reviewer') }
    if ([string](Get-VsatProp $Mapping 'reviewedUtc' '') -notmatch '^\d{4}-\d{2}-\d{2}') { $why.Add('no review date') }
    if (-not [string](Get-VsatProp $Mapping 'sourceRef' '')) { $why.Add('no source reference') }
    $fw = @($Catalogs.frameworks | Where-Object { $_.id -eq [string](Get-VsatProp $Mapping 'framework' '') })[0]
    if (-not $fw) { $why.Add('unknown framework') }
    elseif ([string]$fw.edition -match '(?i)^\s*$|to be confirmed|unknown|tbd|none imported') { $why.Add('framework edition not confirmed') }
    return @($why)
}

function ConvertTo-VsatCrosswalk {
    param([Parameter(Mandatory)]$Catalogs, [Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Mappings)
    $byRule = @{}; $byControl = @{}; $fws = [ordered]@{}
    foreach ($f in @($Catalogs.frameworks)) { $fws[[string]$f.id] = $f }
    $all = foreach ($src in $Mappings) {
        $m = [ordered]@{}; foreach ($k in $src.Keys) { $m[$k] = $src[$k] }
        $why = @(Test-VsatMappingProvenance -Mapping $m -Catalogs $Catalogs)
        if ($why.Count) { $m.status = 'proposed'; $m.demoted = "verified claim without provenance ($($why -join ', '))" }
        if (-not $byRule.ContainsKey($m.ruleId)) { $byRule[$m.ruleId] = [System.Collections.Generic.List[object]]::new() }
        $byRule[$m.ruleId].Add($m)
        $k = "$($m.framework)|$($m.control)"
        if (-not $byControl.ContainsKey($k)) { $byControl[$k] = [System.Collections.Generic.List[object]]::new() }
        $byControl[$k].Add($m)
        $m
    }
    return [ordered]@{ catalogs = $Catalogs; frameworks = $fws; mappings = @($all); byRule = $byRule; byControl = $byControl }
}

function Get-VsatCrosswalk {
    if ($script:VsatCrosswalkCache) { return $script:VsatCrosswalkCache }
    $cat = ConvertFrom-VsatJson (Get-VsatEmbeddedText 'data/frameworks/catalogs.json')
    $x = ConvertFrom-VsatJson (Get-VsatEmbeddedText 'data/frameworks/crosswalk.json')
    $script:VsatCrosswalkCache = ConvertTo-VsatCrosswalk -Catalogs $cat -Mappings @($x.mappings)
    return $script:VsatCrosswalkCache
}

function Get-VsatRuleCrosswalkRefs {
    # Crosswalk rows of one rule in the shape of rule.frameworks entries.
    param([Parameter(Mandatory)][string]$RuleId)
    $cw = Get-VsatCrosswalk
    return @(foreach ($m in @($cw.byRule[$RuleId])) {
            if (-not $m) { continue }
            $fw = $cw.frameworks[[string]$m.framework]
            [ordered]@{ framework = [string]$fw.name; frameworkId = [string]$m.framework; edition = [string]$fw.edition; control = [string]$m.control; relation = [string]$m.relation; mappingStatus = [string]$m.status; sourceRef = [string](Get-VsatProp $m 'sourceRef' '') }
        })
}

function Get-VsatControlLabel {
    # Paraphrase from the catalog; ATT&CK mitigation names come from the pinned ATT&CK catalog.
    param([Parameter(Mandatory)]$Framework, [Parameter(Mandatory)][string]$Control)
    foreach ($c in @($Framework.controls)) { if ($c -and [string]$c.id -eq $Control) { return [string](Get-VsatProp $c 'paraphrase' '') } }
    if ([string]$Framework.id -eq 'mitre-attack-mitigations') {
        $mit = (Get-VsatAttackCatalog).mitigations
        if ($mit.Contains($Control)) { return [string]$mit[$Control].name }
    }
    return ''
}

function ConvertTo-VsatControlSortKey {
    # Natural order: AC-2 before AC-11, SR 1.2 before SR 1.11.
    param([string]$Id)
    return [regex]::Replace([string]$Id, '\d+', { param($m) $m.Value.PadLeft(6, '0') })
}
#endregion Compliance crosswalk

#region Sign-off and exception registers
function Get-VsatFindingAssetRef {
    param($Finding)
    $a = Get-VsatAsset -Id ([string]$Finding.assetId)
    if ($a) { return $a }
    return [ordered]@{ id = $Finding.assetId; name = $Finding.assetName; type = $Finding.assetType; tags = @(); zone = $null }
}

function Test-VsatRegisterAsset {
    # Sign-off/exception asset selector: empty or * = any; name:/type:/tag:/id:/zone: or a name pattern.
    param($Finding, [string]$Selector)
    if (-not $Selector -or $Selector -eq '*') { return $true }
    if ($Finding.assetName -like $Selector -or $Finding.assetId -like $Selector) { return $true }
    return (Test-VsatAssetMatch -Asset (Get-VsatFindingAssetRef $Finding) -Match $Selector)
}

function ConvertTo-VsatRegisterDate {
    param($Value)
    if (-not $Value) { return $null }
    try { return [DateTime]::Parse([string]$Value, [Globalization.CultureInfo]::InvariantCulture, [Globalization.DateTimeStyles]::AdjustToUniversal) } catch { return $null }
}

function Get-VsatSignoffRegister {
    # One row per (sign-off, matching finding). Only MANUAL findings take sign-offs. States:
    #   valid       complete, current sign-off on a MANUAL finding
    #   expired     past its expires date
    #   incomplete  missing reviewer, date or a known decision
    #   orphan      no finding matches (wrong rule or asset, or the rule is automated and not failing)
    #   conflict    says satisfied on an automated FAIL, or disagrees with another valid sign-off
    # A sign-off never changes a finding's result; it only feeds the control matrix.
    param([Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Findings, $Scope)
    $today = [DateTime]::UtcNow.Date
    $rows = [System.Collections.Generic.List[object]]::new()
    foreach ($s in @(Get-VsatProp $Scope 'signoffs' @())) {
        if (-not $s) { continue }
        $rule = [string](Get-VsatProp $s 'ruleId' ''); $sel = [string](Get-VsatProp $s 'asset' '')
        $decision = [string](Get-VsatProp $s 'decision' '')
        $exp = ConvertTo-VsatRegisterDate (Get-VsatProp $s 'expires')
        $flags = [System.Collections.Generic.List[string]]::new()
        if (-not [string](Get-VsatProp $s 'reviewer' '')) { $flags.Add('no-reviewer') }
        if (-not (ConvertTo-VsatRegisterDate (Get-VsatProp $s 'dateUtc'))) { $flags.Add('no-date') }
        if ($decision -notin @('satisfied', 'not-satisfied', 'not-applicable')) { $flags.Add('unknown-decision') }
        if (-not [string](Get-VsatProp $s 'evidenceRef' '')) { $flags.Add('no-evidence-ref') }
        $expired = ($exp -and $exp.Date -lt $today)
        $base = { param($f, [string]$state) [ordered]@{ findingKey = $(if ($f) { $f.key } else { $null }); ruleId = $rule; asset = $sel; assetName = $(if ($f) { $f.assetName } else { $null }); result = $(if ($f) { $f.result } else { $null }); reviewer = (Get-VsatProp $s 'reviewer' ''); decision = $decision; evidenceRef = (Get-VsatProp $s 'evidenceRef' ''); dateUtc = (Get-VsatProp $s 'dateUtc' ''); expires = (Get-VsatProp $s 'expires' ''); state = $state; flags = @($flags) } }
        $hits = @($Findings | Where-Object { $rule -and $_.ruleId -like $rule -and (Test-VsatRegisterAsset -Finding $_ -Selector $sel) })
        $manual = @($hits | Where-Object { $_.result -eq 'MANUAL' })
        if ($manual.Count) {
            $st = if (@($flags | Where-Object { $_ -ne 'no-evidence-ref' }).Count) { 'incomplete' } elseif ($expired) { 'expired' } else { 'valid' }
            foreach ($f in $manual) { $rows.Add((& $base $f $st)) }
            continue
        }
        $fails = @($hits | Where-Object { $_.result -eq 'FAIL' })
        if ($fails.Count -and $decision -ne 'not-satisfied') { foreach ($f in $fails) { $rows.Add((& $base $f 'conflict')) }; continue }
        $rows.Add((& $base $null 'orphan'))
    }
    # Two valid sign-offs that disagree on one finding cannot both stand.
    foreach ($g in @($rows | Where-Object { $_.state -eq 'valid' } | Group-Object { $_.findingKey })) {
        if (@($g.Group | ForEach-Object { $_.decision } | Sort-Object -Unique).Count -gt 1) { foreach ($r in $g.Group) { $r.state = 'conflict' } }
    }
    return @($rows)
}

function Get-VsatExceptionRegister {
    # Scope exceptions with their register flags: unapproved (no approver), expired, no-expiry and
    # orphan (matches no finding). Only an active, approved exception makes a FAIL "excepted" in
    # the control matrix; the finding itself stays FAIL.
    param([Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Findings, $Scope)
    $today = [DateTime]::UtcNow.Date
    return @(foreach ($ex in @(Get-VsatProp $Scope 'exceptions' @())) {
            if (-not $ex) { continue }
            $rule = [string](Get-VsatProp $ex 'ruleId' ''); $pat = [string](Get-VsatProp $ex 'asset' '*')
            if (-not $pat) { $pat = '*' }
            $exp = ConvertTo-VsatRegisterDate (Get-VsatProp $ex 'expires')
            $active = ($null -eq $exp -or $exp.Date -ge $today)
            $hits = @($Findings | Where-Object { $rule -and $_.ruleId -like $rule -and ($_.assetName -like $pat -or $_.assetId -like $pat) })
            $flags = [System.Collections.Generic.List[string]]::new()
            if (-not [string](Get-VsatProp $ex 'approver' '')) { $flags.Add('unapproved') }
            if (-not $active) { $flags.Add('expired') }
            if (-not (Get-VsatProp $ex 'expires')) { $flags.Add('no-expiry') }
            if (-not $hits.Count) { $flags.Add('orphan') }
            [ordered]@{
                ruleId = $rule; asset = $pat; owner = (Get-VsatProp $ex 'owner' ''); approver = (Get-VsatProp $ex 'approver' ''); rationale = (Get-VsatProp $ex 'rationale' '')
                compensatingControl = (Get-VsatProp $ex 'compensatingControl' ''); ticket = (Get-VsatProp $ex 'ticket' ''); expires = (Get-VsatProp $ex 'expires' '')
                active = $active; findings = $hits.Count; failing = @($hits | Where-Object { $_.result -eq 'FAIL' }).Count; flags = @($flags)
            }
        })
}
#endregion Sign-off and exception registers

#region Control matrix
function Get-VsatControlState {
    # Precedence (worst wins); a control is never satisfied with missing evidence:
    #  1 unexcepted FAIL or a manual "not-satisfied" sign-off   -> not-satisfied
    #  2 any UNKNOWN or ERROR                                    -> not-assessed
    #  3 open MANUAL: alone -> manual-open, with positives -> partial
    #  4 approved active exception: alone -> excepted, with positives -> partial
    #  5 only signed-off MANUAL -> manual-signed-off
    #  6 PASS (with or without signed-off MANUAL) -> satisfied
    #  7 nothing but NOT_APPLICABLE, or no finding at all -> not-assessed
    param([Parameter(Mandatory)][System.Collections.IDictionary]$Counts)
    $n = { param($k) [int](Get-VsatProp $Counts $k 0) }
    if ((& $n 'FAIL') -gt 0 -or (& $n 'SIGNED_NOT_SATISFIED') -gt 0) { return 'not-satisfied' }
    if ((& $n 'UNKNOWN') -gt 0 -or (& $n 'ERROR') -gt 0) { return 'not-assessed' }
    $pos = (& $n 'PASS') + (& $n 'SIGNED_OFF')
    $open = (& $n 'MANUAL') - (& $n 'SIGNED_OFF') - (& $n 'SIGNED_NOT_SATISFIED')
    if ($open -gt 0) { if ($pos -gt 0 -or (& $n 'EXCEPTED') -gt 0) { return 'partial' }; return 'manual-open' }
    if ((& $n 'EXCEPTED') -gt 0) { if ($pos -gt 0) { return 'partial' }; return 'excepted' }
    if ((& $n 'SIGNED_OFF') -gt 0 -and (& $n 'PASS') -eq 0) { return 'manual-signed-off' }
    if ($pos -gt 0) { return 'satisfied' }
    return 'not-assessed'
}

function Get-VsatControlMatrix {
    # Rows { control, paraphrase, rules, assets, state, counts, mappingStatus, mappingStatuses } for one
    # framework. mappingStatus is verified only when every mapping behind the control is verified.
    param([Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Findings, [Parameter(Mandatory)][string]$FrameworkId, [AllowEmptyCollection()][object[]]$Signoffs = @())
    $cw = Get-VsatCrosswalk
    $fw = $cw.frameworks[$FrameworkId]
    if (-not $fw) { return @() }
    $byRule = @{}
    foreach ($f in $Findings) { if (-not $byRule.ContainsKey($f.ruleId)) { $byRule[$f.ruleId] = [System.Collections.Generic.List[object]]::new() }; $byRule[$f.ruleId].Add($f) }
    $sig = @{}; foreach ($s in @($Signoffs)) { if ($s -and $s.state -eq 'valid' -and $s.findingKey) { $sig[[string]$s.findingKey] = [string]$s.decision } }
    $controls = [ordered]@{}
    foreach ($m in @($cw.mappings | Where-Object { $_.framework -eq $FrameworkId })) {
        if (-not $controls.Contains([string]$m.control)) { $controls[[string]$m.control] = [System.Collections.Generic.List[object]]::new() }
        $controls[[string]$m.control].Add($m)
    }
    $rows = foreach ($ctl in $controls.Keys) {
        $maps = $controls[$ctl]
        $rules = @($maps | ForEach-Object { [string]$_.ruleId } | Sort-Object -Unique)
        $c = [ordered]@{ PASS = 0; FAIL = 0; MANUAL = 0; UNKNOWN = 0; ERROR = 0; NOT_APPLICABLE = 0; EXCEPTED = 0; SIGNED_OFF = 0; SIGNED_NOT_SATISFIED = 0 }
        $assets = @{}
        foreach ($rid in $rules) {
            foreach ($f in @($byRule[$rid])) {
                if (-not $f) { continue }
                $assets[[string]$f.assetId] = $true
                switch ([string]$f.result) {
                    'FAIL' { if ($f.exception -and $f.exception.active -and [string](Get-VsatProp $f.exception 'approver' '')) { $c.EXCEPTED++ } else { $c.FAIL++ } }
                    'MANUAL' {
                        $c.MANUAL++
                        $d = $sig[[string]$f.key]
                        if ($d -in @('satisfied', 'not-applicable')) { $c.SIGNED_OFF++ } elseif ($d -eq 'not-satisfied') { $c.SIGNED_NOT_SATISFIED++ }
                    }
                    default { if ($c.Contains([string]$f.result)) { $c[[string]$f.result]++ } }
                }
            }
        }
        $statuses = @($maps | ForEach-Object { [string]$_.status } | Sort-Object -Unique)
        [ordered]@{
            control = $ctl; paraphrase = (Get-VsatControlLabel -Framework $fw -Control $ctl); rules = $rules; assets = $assets.Count
            state = (Get-VsatControlState -Counts $c); counts = $c
            mappingStatus = $(if ($statuses.Count -eq 1 -and $statuses[0] -eq 'verified') { 'verified' } else { 'unverified' }); mappingStatuses = $statuses
        }
    }
    return @($rows | Sort-Object { ConvertTo-VsatControlSortKey $_.control } -Culture ([Globalization.CultureInfo]::InvariantCulture))
}

function Get-VsatComplianceResults {
    # results.compliance: per framework the matrix plus headline counts that keep verified and
    # unverified mappings apart; the sign-off and exception registers.
    param([Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Findings, $Scope)
    $cw = Get-VsatCrosswalk
    $signoffs = @(Get-VsatSignoffRegister -Findings $Findings -Scope $Scope)
    $exceptions = @(Get-VsatExceptionRegister -Findings $Findings -Scope $Scope)
    $frameworks = foreach ($fw in $cw.frameworks.Values) {
        $maps = @($cw.mappings | Where-Object { $_.framework -eq $fw.id })
        $rows = @(Get-VsatControlMatrix -Findings $Findings -FrameworkId $fw.id -Signoffs $signoffs)
        $states = [ordered]@{ verified = [ordered]@{}; unverified = [ordered]@{} }
        foreach ($s in $script:VsatMatrixStates) { $states.verified[$s] = 0; $states.unverified[$s] = 0 }
        foreach ($r in $rows) { $states[$r.mappingStatus][$r.state]++ }
        $ms = [ordered]@{ verified = 0; proposed = 0; derived = 0 }
        foreach ($m in $maps) { $ms[[string]$m.status] = [int]$ms[[string]$m.status] + 1 }
        $o = [ordered]@{
            id = $fw.id; name = $fw.name; edition = $fw.edition; publisher = (Get-VsatProp $fw 'publisher' ''); license = $fw.license; note = (Get-VsatProp $fw 'note' '')
            importRequired = ([bool](Get-VsatProp $fw 'importRequired' $false) -or $maps.Count -eq 0)
            verifiedMappings = [int]$ms.verified; unverifiedMappings = $maps.Count - [int]$ms.verified; mappingStatuses = $ms
            rulesMapped = @($maps | ForEach-Object { $_.ruleId } | Sort-Object -Unique).Count
            states = $states; controls = $rows
        }
        # Pinned source (DISA package name and SHA-256). URLs stay in the catalog: the report links nowhere.
        $src = Get-VsatProp $fw 'source' $null
        if ($src) { $o.source = [ordered]@{ package = $src.package; sha256 = $src.sha256 } }
        $o
    }
    return [ordered]@{
        states = $script:VsatMatrixStates
        note = 'Unverified rows (proposed or derived mappings) are shown separately and never count toward a verified result. Missing evidence is never satisfied.'
        frameworks = @($frameworks); signoffs = $signoffs; exceptions = $exceptions
    }
}
#endregion Control matrix

#region Audit pack
function Get-VsatControlMatrixRows {
    param([Parameter(Mandatory)]$Results)
    foreach ($fw in @(Get-VsatProp $Results 'compliance.frameworks' @())) {
        foreach ($c in @($fw.controls)) {
            [ordered]@{
                framework = $fw.id; frameworkName = $fw.name; edition = $fw.edition; control = $c.control; description = $c.paraphrase; state = $c.state
                mappingStatus = $c.mappingStatus; mappingStatuses = (@($c.mappingStatuses) -join '; '); rules = (@($c.rules) -join '; '); assets = $c.assets
                PASS = $c.counts.PASS; FAIL = $c.counts.FAIL; EXCEPTED = $c.counts.EXCEPTED; MANUAL = $c.counts.MANUAL; SIGNED_OFF = $c.counts.SIGNED_OFF
                SIGNED_NOT_SATISFIED = $c.counts.SIGNED_NOT_SATISFIED; UNKNOWN = $c.counts.UNKNOWN; ERROR = $c.counts.ERROR; NOT_APPLICABLE = $c.counts.NOT_APPLICABLE
            }
        }
    }
}

function Write-VsatAuditPack {
    # -AuditPack: audit-pack/ next to the evidence package. Plain files only (CSV, HTML, JSON and a
    # copy of the package); manifest.json hashes every file and repeats the package's receipt code.
    # Runs after Write-VsatOutputs, so assessment.vsat.zip and its receipt already exist.
    param([Parameter(Mandatory)]$Results, [Parameter(Mandatory)][string]$OutputDir)
    $dir = Join-Path $OutputDir 'audit-pack'
    if (-not (Test-Path -LiteralPath $dir)) { [void](New-Item -ItemType Directory -Path $dir -Force) }
    $zip = Join-Path $OutputDir 'assessment.vsat.zip'
    $receipt = Get-VsatReceipt -Path $zip
    Export-VsatCsv -Rows @(Get-VsatControlMatrixRows -Results $Results) -Columns @('framework', 'frameworkName', 'edition', 'control', 'description', 'state', 'mappingStatus', 'mappingStatuses', 'rules', 'assets', 'PASS', 'FAIL', 'EXCEPTED', 'MANUAL', 'SIGNED_OFF', 'SIGNED_NOT_SATISFIED', 'UNKNOWN', 'ERROR', 'NOT_APPLICABLE') -Path (Join-Path $dir 'control-matrix.csv')
    $sig = @(foreach ($s in @(Get-VsatProp $Results 'compliance.signoffs' @())) { $o = [ordered]@{}; foreach ($k in $s.Keys) { $o[$k] = $s[$k] }; $o.flags = (@($s.flags) -join '; '); $o })
    Export-VsatCsv -Rows $sig -Columns @('state', 'ruleId', 'asset', 'findingKey', 'assetName', 'result', 'reviewer', 'decision', 'evidenceRef', 'dateUtc', 'expires', 'flags') -Path (Join-Path $dir 'signoffs.csv')
    $exc = @(foreach ($x in @(Get-VsatProp $Results 'compliance.exceptions' @())) { $o = [ordered]@{}; foreach ($k in $x.Keys) { $o[$k] = $x[$k] }; $o.flags = (@($x.flags) -join '; '); $o })
    Export-VsatCsv -Rows $exc -Columns @('ruleId', 'asset', 'owner', 'approver', 'rationale', 'compensatingControl', 'ticket', 'expires', 'active', 'findings', 'failing', 'flags') -Path (Join-Path $dir 'exceptions.csv')
    Write-VsatFile -Path (Join-Path $dir 'control-matrix.html') -Content (New-VsatControlMatrixHtml -Results $Results -Receipt $receipt)
    Copy-Item -LiteralPath $zip -Destination (Join-Path $dir 'assessment.vsat.zip') -Force
    $names = @('control-matrix.csv', 'control-matrix.html', 'signoffs.csv', 'exceptions.csv', 'assessment.vsat.zip')
    $manifest = [ordered]@{
        schemaVersion = $script:VsatSchemaVersion
        tool = [ordered]@{ name = 'VSAT'; version = $script:VsatVersion; buildCommit = $script:VsatBuildCommit }
        kind = 'audit-pack'; runId = $Results.run.id; generatedUtc = (Get-VsatUtcNow); statusLabel = $Results.status.label
        package = [ordered]@{ name = 'assessment.vsat.zip'; sha256 = (Get-VsatSha256 -Path $zip); bytes = (Get-Item -LiteralPath $zip).Length }
        receipt = $receipt
        receiptNote = 'Receipt of the evidence package copied here. Verify with: vsat.ps1 -Replay assessment.vsat.zip -Receipt <code>.'
        frameworks = @(foreach ($fw in @(Get-VsatProp $Results 'compliance.frameworks' @())) { [ordered]@{ id = $fw.id; edition = $fw.edition; verifiedMappings = $fw.verifiedMappings; unverifiedMappings = $fw.unverifiedMappings; importRequired = $fw.importRequired } })
        files = @($names | ForEach-Object { $p = Join-Path $dir $_; [ordered]@{ name = $_; sha256 = (Get-VsatSha256 -Path $p); bytes = (Get-Item -LiteralPath $p).Length } })
        note = 'SHA-256 hashes provide integrity checking of these files, not proof that source systems reported truthfully. Unverified mappings are proposals, not certification. Contains sensitive infrastructure data.'
    }
    Write-VsatFile -Path (Join-Path $dir 'manifest.json') -Content (ConvertTo-VsatJson $manifest)
    Write-VsatLog -Source 'audit-pack' -Message "Audit pack written to $dir (receipt $receipt)"
    return @($names + 'manifest.json' | ForEach-Object { "audit-pack/$_" })
}

$script:VsatMatrixStateLabel = [ordered]@{ 'not-satisfied' = 'Not satisfied'; 'not-assessed' = 'Not assessed'; 'manual-open' = 'Manual, open'; 'excepted' = 'Excepted'; 'partial' = 'Partial'; 'manual-signed-off' = 'Manual, signed off'; 'satisfied' = 'Satisfied' }

function New-VsatControlMatrixHtml {
    # Standalone, offline control matrix. Rendered here as static HTML (every value HTML-encoded), so
    # the page needs no script at all: the CSP allows only the report stylesheet, by hash.
    param([Parameter(Mandatory)]$Results, [string]$Receipt)
    $e = { param($v) [System.Net.WebUtility]::HtmlEncode([string]$v) }
    $css = Get-VsatEmbeddedText 'assets/report/report.css'
    $csp = "default-src 'none'; style-src 'sha256-$(Get-VsatSha256Base64 $css)'; img-src data:; base-uri 'none'; form-action 'none'"
    $cmp = Get-VsatProp $Results 'compliance' $null
    $sb = [System.Text.StringBuilder]::new()
    $st = { param([string]$s) "<span class=`"cm-state cm-st-$s`">$(& $e $script:VsatMatrixStateLabel[$s])</span>" }
    $n = { param($v) if ([int]$v) { (& $e $v) } else { '<span class="muted">0</span>' } }
    [void]$sb.Append("<!DOCTYPE html>`n<html lang=`"en`">`n<head>`n<meta charset=`"utf-8`">`n<meta http-equiv=`"Content-Security-Policy`" content=`"$csp`">`n<meta name=`"referrer`" content=`"no-referrer`">`n<meta name=`"viewport`" content=`"width=device-width, initial-scale=1`">`n<meta name=`"color-scheme`" content=`"light dark`">`n<meta name=`"robots`" content=`"noindex, nofollow`">`n<title>VSAT control matrix</title>`n<style>$css</style>`n</head>`n<body>`n")
    [void]$sb.Append('<header class="app-header"><div class="brand"><svg class="brand-mark" viewBox="0 0 24 28" width="24" height="28" aria-hidden="true" focusable="false"><path d="M12 1 L22 5 V13 C22 20 17.5 24.8 12 27 C6.5 24.8 2 20 2 13 V5 Z" fill="currentColor"/><path d="M7.5 13.5 L10.8 16.8 L16.8 10.2" fill="none" stroke="#ffffff" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg><span class="wordmark">VSAT</span><span class="brand-sub">Control matrix</span></div>')
    [void]$sb.Append("<dl class=`"run-meta`"><div><dt>Version</dt><dd id=`"meta-version`">VSAT $(& $e $script:VsatVersion)</dd></div><div><dt>Generated</dt><dd>$(& $e (([string]$Results.generatedUtc) -replace '^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}).*$', '$1 $2 UTC'))</dd></div><div><dt>Run</dt><dd class=`"mono`">$(& $e $Results.run.id)</dd></div>")
    if ($Receipt) { [void]$sb.Append("<div><dt>Receipt</dt><dd class=`"mono`">$(& $e $Receipt)</dd></div>") }
    [void]$sb.Append('</dl><div class="header-actions"><p class="sensitive-note" role="note">Sensitive data</p></div></header>' + "`n<main id=`"main`">`n")
    [void]$sb.Append("<div class=`"page-head`"><div><h1>Control matrix</h1><p>$(& $e $Results.status.label). One row per framework control with at least one VSAT rule mapped to it.</p></div></div>`n")
    [void]$sb.Append("<div class=`"notice notice-info`" role=`"note`"><strong>How to read this</strong>$(& $e (Get-VsatProp $cmp 'note' '')) A control is satisfied only when every mapped check passed or was signed off; UNKNOWN or ERROR makes it not assessed. Mapping rows marked unverified are proposals for a reviewer, not certification.</div>`n")
    [void]$sb.Append('<section class="card section"><h2>Frameworks</h2><div class="table-wrap"><table><thead><tr><th>Framework</th><th>Edition</th><th class="num" title="Mappings with reviewer, date, edition and source reference">Verified</th><th class="num" title="Proposed or derived mappings">Unverified</th><th>Controls, verified mappings</th><th>Controls, unverified mappings</th></tr></thead><tbody>')
    $summ = {
        param($counts)
        $parts = @(foreach ($s in $script:VsatMatrixStates) { if ([int]$counts[$s]) { "<span class=`"nowrap`">$(& $st $s) $([int]$counts[$s])</span>" } })
        if ($parts.Count) { $parts -join ' ' } else { '<span class="muted">none</span>' }
    }
    foreach ($fw in @(Get-VsatProp $cmp 'frameworks' @())) {
        $name = if ($fw.importRequired) { "$(& $e $fw.name) <span class=`"cm-import`">Import required</span>" } else { & $e $fw.name }
        [void]$sb.Append("<tr><td><a href=`"#fw-$(& $e $fw.id)`">$name</a></td><td>$(& $e $fw.edition)</td><td class=`"num`">$(& $e $fw.verifiedMappings)</td><td class=`"num`">$(& $e $fw.unverifiedMappings)</td><td>$(& $summ $fw.states.verified)</td><td>$(& $summ $fw.states.unverified)</td></tr>")
    }
    [void]$sb.Append("</tbody></table></div></section>`n")
    foreach ($fw in @(Get-VsatProp $cmp 'frameworks' @())) {
        [void]$sb.Append("<section class=`"card section cm-matrix`" id=`"fw-$(& $e $fw.id)`"><div class=`"card-head`"><h2>$(& $e $fw.name)</h2><span class=`"muted small`">$(& $e $fw.edition) &middot; $(& $e $fw.publisher)</span></div>")
        if ($fw.note) { [void]$sb.Append("<p class=`"small muted`">$(& $e $fw.note)</p>") }
        if ($fw.source) { [void]$sb.Append("<p class=`"small muted`">Source: <span class=`"mono`">$(& $e $fw.source.package)</span>, SHA-256 <span class=`"mono break`">$(& $e $fw.source.sha256)</span></p>") }
        if ($fw.importRequired) {
            [void]$sb.Append("<div class=`"notice notice-warn`" role=`"note`"><strong>Import required</strong>VSAT ships no mappings for this framework. See docs/compliance-mapping.md.</div></section>`n")
            continue
        }
        [void]$sb.Append('<div class="table-wrap"><table><thead><tr><th>Control</th><th>State</th><th>Mapping</th><th>VSAT rules</th><th class="num">Assets</th><th class="num">Pass</th><th class="num">Fail</th><th class="num">Excepted</th><th class="num">Manual / signed</th><th class="num">Unknown</th><th class="num">N/A</th></tr></thead><tbody>')
        foreach ($c in @($fw.controls)) {
            $map = if ($c.mappingStatus -eq 'verified') { '<span class="verified">verified</span>' } else { "<span class=`"unverified`">$(& $e (@($c.mappingStatuses) -join ', '))</span>" }
            [void]$sb.Append("<tr><td class=`"cm-ctl`"><span class=`"mono`">$(& $e $c.control)</span><span class=`"sub`">$(& $e $c.paraphrase)</span></td><td>$(& $st $c.state)</td><td>$map</td><td class=`"small`"><details class=`"cm-rules`"><summary>$(@($c.rules).Count) rule$(if (@($c.rules).Count -ne 1) { 's' })</summary><span class=`"mono break`">$(& $e (@($c.rules) -join ', '))</span></details></td><td class=`"num`">$(& $e $c.assets)</td><td class=`"num`">$(& $n $c.counts.PASS)</td><td class=`"num`">$(& $n $c.counts.FAIL)</td><td class=`"num`">$(& $n $c.counts.EXCEPTED)</td><td class=`"num`">$(& $n $c.counts.MANUAL) / $([int]$c.counts.SIGNED_OFF)</td><td class=`"num`">$(& $n ([int]$c.counts.UNKNOWN + [int]$c.counts.ERROR))</td><td class=`"num`">$(& $n $c.counts.NOT_APPLICABLE)</td></tr>")
        }
        [void]$sb.Append("</tbody></table></div></section>`n")
    }
    $reg = {
        param([string]$Title, [object[]]$Rows, [string[]]$Cols, [string[]]$Labels, [string]$Empty)
        [void]$sb.Append("<section class=`"card section`"><h2>$(& $e $Title) ($(@($Rows).Count))</h2>")
        if (-not @($Rows).Count) { [void]$sb.Append("<p class=`"muted`">$(& $e $Empty)</p></section>`n"); return }
        [void]$sb.Append('<div class="table-wrap"><table><thead><tr>' + (($Labels | ForEach-Object { "<th>$(& $e $_)</th>" }) -join '') + '</tr></thead><tbody>')
        foreach ($r in $Rows) { [void]$sb.Append('<tr>' + (($Cols | ForEach-Object { $v = $r[$_]; if ($v -is [array]) { $v = $v -join ', ' }; "<td class=`"break`">$(& $e $v)</td>" }) -join '') + '</tr>') }
        [void]$sb.Append("</tbody></table></div></section>`n")
    }
    & $reg 'Sign-offs' @(Get-VsatProp $cmp 'signoffs' @()) @('state', 'ruleId', 'assetName', 'reviewer', 'decision', 'evidenceRef', 'dateUtc', 'expires', 'flags') @('State', 'Rule', 'Asset', 'Reviewer', 'Decision', 'Evidence', 'Date', 'Expires', 'Flags') 'No sign-offs in the scope file (scope key signoffs).'
    & $reg 'Exceptions' @(Get-VsatProp $cmp 'exceptions' @()) @('ruleId', 'asset', 'owner', 'approver', 'compensatingControl', 'ticket', 'expires', 'findings', 'flags') @('Rule', 'Asset', 'Owner', 'Approver', 'Compensating control', 'Ticket', 'Expires', 'Findings', 'Flags') 'No exceptions in the scope file (scope key exceptions).'
    [void]$sb.Append("</main>`n</body>`n</html>`n")
    return $sb.ToString()
}
#endregion Audit pack
